### ISSUE TITLE
Setup bug

### ISSUE THREAD

**Issue by Benoist3012** [akowald/StopThatTank#5]
When I was playing on your server, I destroyed my lvl 3 teleporters, and built a new one.
You know when a teleporter is broke, the second one is reset to level one. And so I rebuilded my exit teleporters and it ended up on this: http://images.akamai.steamusercontent.com/ugc/485640524937862336/3EF811F70F38D5F659C3FCA0BFF2BE43236389F3/

I guess when you force the level on the teleporter, do the same thing for the other one.

I have also noticed you didn't block the points for teleporting during setup, so I was able to farm them with a friend.

**Comment by Benoist3012** [comment]
Closed the plugin developer seems to ignore this issue.

**Comment by akowald** [comment]
Don't worry, I saw this. Was just waiting to post when I had some resolution. It'll be fixed in the next version. I already fixed the point farming on the official server but it's a problem to take up with hlstatsx:ce. I recommend removing the building constructed/destructed actions on the web panel.

**Comment by Benoist3012** [comment]
Oh I'm so sorry, I didn't want to leave an issue open here.
And about points farning it's not only for hlstatsx it also give me a point on the scoreboard everytime someone takes my teleporter.

**Comment by akowald** [comment]
Calling quickbuild on both teles seems to fix the problem. Thanks for reporting it!
